services:
  super-note:
    image: {{DOCKERHUB_REPO}}:{{IMAGE_TAG}}
    container_name: super-note
    restart: unless-stopped
    ports:
      - "3501:3001"
    volumes:
      - "/var/apps/super-note/shares/super-note/data:/app/data"
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/data/super-note.db
      - PORT=3001
